version: "3.9"

services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: my-go-backend
    ports:
      - "3000:3000"
    # ENV-переменные для бэкенда (если нужны)
    environment:
      - SOME_ENV=example

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: my-react-frontend
    ports:
      - "8080:80"
    depends_on:
      - web